# Generated by Django 4.2.11 on 2024-04-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_laundryitem_options_alter_bag_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laundryitem',
            name='description',
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('cleaning_service', 'Cleaning Service'), ('customer', 'Customer')], default='customer', max_length=200),
        ),
    ]
